version: 0.1
CLOUDFRONT_DISTRIBUTION_ID: "/cloudfront/E39J316EZD2MTO"

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm run build  # Builds the project
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
artifacts:
  files:
    - '**/*'
  base-directory: build  # Directory with output files (e.g., React app) 
