version: 0.1

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm run build
      - aws cloudfront create-invalidation --distribution-id E39J316EZD2MTO --paths "/*"
artifacts:
  files:
    - '**/*'
  base-directory: build  # Directory with output files (e.g., React app) 
